# Generated by Django 4.2.16 on 2024-12-15 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DateTimeEntryShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.datetimeentry')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.JSONField(default=dict)),
                ('belonged_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='facility.facility')),
                ('reservation_available_dates', models.ManyToManyField(through='field.DateTimeEntryShip', to='field.datetimeentry')),
            ],
        ),
        migrations.AddField(
            model_name='datetimeentryship',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field'),
        ),
    ]
