# Generated by Django 4.2.16 on 2024-10-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('field_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('open_address', models.CharField(max_length=100)),
                ('maps_location', models.CharField(max_length=100)),
                ('reservation_hours', models.CharField(max_length=100)),
                ('shoes', models.CharField(max_length=100)),
            ],
        ),
    ]
