# Generated by Django 4.2.16 on 2024-10-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('open_address', models.CharField(max_length=100)),
                ('maps_location', models.URLField()),
                ('reservation_hours', models.CharField(max_length=100)),
                ('is_have_shoes', models.BooleanField()),
            ],
        ),
    ]
