# Generated by Django 4.2.16 on 2024-11-13 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_alter_field_reservation_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='field',
            name='reservation_hours',
        ),
        migrations.CreateModel(
            name='DateTimeEntryShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.datetimeentry')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field')),
            ],
        ),
        migrations.AddField(
            model_name='field',
            name='reservation_available_dates',
            field=models.ManyToManyField(through='field.DateTimeEntryShip', to='field.datetimeentry'),
        ),
    ]
